config/routes.rb
Rails.application.routes.draw do
  resources :review_years
  root to: "reviews#index"

  scope ':commentable_type' do
    resources :comments
  end

  resources :reviews do
    collection do
      delete :destroy
    end
  end

  resources :users do
    resources :reviews, controller: "users/reviews"
    put "settings", to: "users/settings#update"
  end


  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_commentable
  validates :salary, numericality: true
  validates :level, numericality: true
  devise :rememberable, :trackable, :omniauthable, :omniauth_providers => [:google_oauth2]

  has_many :reviews_for, class_name: "Review", foreign_key: :reviewee_id
  has_many :reviews_by, class_name: "Review", foreign_key: :reviewer_id
  has_settings :user_settings,
               class_name: "UserSetting",
               &UserSetting.default_settings_proc

  def self.find_for_google_oauth2(access_token, _ = nil)
    data = access_token.info
    user = User.where(:email => data['email']).first_or_initialize(new_user_params(data))
    user.save
    user
  end

  def self.new_user_params(data)
    {
        image: data['image'],
        name: data['first_name'],
        salary: 0,
        level: 0
    }
  end

  def all_but_me
    User.where.not(id: self.id)
  end

  def reviews_pending_for
    Review.pending.where(reviewee: self)
  end

  def reviews_done_for
    Review.done.where(reviewee: self)
  end

  def needs_to_write_reviews_for
    Review.pending.where(reviewer: self)
  end

  def only_full_reviews_done_for
    Review.done.where(reviewee: self, is_level_only: false)
  end

  def only_review_levels_done_for
    Review.done.where(reviewee: self, is_level_only: true)
  end

  def average_suggested_level
    self.reviews_for.done.average(:suggested_level)
  end

  def stdev_suggested_level
    suggested_levels = self.reviews_for.done.map(&:suggested_level).compact
    suggested_levels.stdev if suggested_levels.present? && suggested_levels.count > 1
  end

  def can_view_suggested_level_for_user?(user)
    pending_reviews_for = self.reviews_by.pending.pluck(:reviewee_id)
    !pending_reviews_for.include?(user.id)
  end

  def grouped_comments
    self.comment_threads.decorate.group_by(&:parent_id)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  skip_before_action :ensure_user_logged_in

  def new_session_path(scope)
    new_user_session_path
  end

  def google_oauth2
    @user = User.find_for_google_oauth2(request.env['omniauth.auth'], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
      sign_in_and_redirect @user, :event => :authentication
    else
      session['devise.google_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/reviews_controller.rb
class Users::ReviewsController < ApplicationController
  def index
    @users = User.all.decorate
  end

  def edit
    @review = Review.find(params[:id]).decorate
  end

  def show
    @review = Review.find(params[:id]).decorate
    @comment = Comment.build_from(@review, current_user.id, nil)
  end

  def update
    @review = Review.find(params[:id])

    if params.key?(:abstain)
      @review.destroy!
      redirect_to :root, notice: 'Review removed successfully!' and return
    end

    @review.assign_attributes(update_if_level_only_review(update_status(review_params)))

    if @review.save
      redirect_to user_review_path(current_user, @review.id), notice: 'Review saved successfully!'
    else
      render :edit
    end
  end

  private

  def update_if_level_only_review(review_params)
    if review_params[:text].strip.blank? && !review_params[:suggested_level].blank?
      review_params.merge(is_level_only: true)
    else
      review_params.merge!(is_level_only: false)
    end

    review_params
  end

  def update_status(review_params)
    if params.key?(:pending)
      review_params.merge!(status: 'pending')
    elsif params.key?(:done)
      review_params.merge!(status: 'done')
    end

    review_params
  end

  def review_params
    params.require(:review).permit(:text, :suggested_level, :is_level_only)
  end
end

app/controllers/users/settings_controller.rb
class Users::SettingsController < ApplicationController
  def update
    current_user.settings(:user_settings).color_scheme
    current_user.settings(:user_settings).update!(color_scheme: params.require(:color_scheme))

    redirect_to :user_reviews
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.decorate
  end

  def show
    @user = User.find(params[:id]).decorate
  end

  def edit
    @user = User.find(params[:id]).decorate
  end

  def update
    @user = User.find(params[:id]).decorate
    if @user.update_attributes(user_params)
      redirect_to users_path, notice: 'User updated!'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:salary, :level, :decided_level)
  end
end

app/views/users/edit.html.erb
<h3>Editing <%= @user.username %></h3>
<%= form_for @user do |f| %>
  <div class="row g-3">
    <div class="col-sm-3">
      <%= f.label "Salary" %>
      <%= f.number_field :salary, class: "form-control" %>
    </div>
    <div class="col-sm-3">
      <%= f.label "Old Level" %>
      <%= f.text_field :level, class: "form-control" %>
    </div>
    <div class="col-sm-3">
      <%= f.label "Decided Level" %>
      <%= f.text_field :decided_level, class: "form-control form-inline" %>
    </div>
    <div class="col-sm-3">
      <br>
      <%= f.submit "Update user", class: "form-control btn btn-dark" %>
    </div>
  </div>
<% end %>

app/views/users/index.html.erb
<ul>

<% @users.each do |user| %>
  <li>
    <%= link_to user.username, user_path(user) %>
  </li>
<% end %>

</ul>

app/views/users/show.html.erb
<h2>
  <%= @user.username %>
  <%= link_to "Edit", edit_user_path(@user), class: "btn btn-dark btn-sm" %>
</h2>


<h3>Reviews <%= @user.username %> has got</h3>
<ul>
<% @user.reviews_for.done.each do |review| %>
  <li><%= link_to review.reviewer.decorate.username, user_review_path(current_user, review) %></li>
<% end %>
</ul>

<h3>Reviews <%= @user.username %> has given</h3>
<ul>
<% @user.reviews_by.done.each do |review| %>
  <li><%= link_to review.reviewee.decorate.username, user_review_path(current_user, review) %></li>
<% end %>
</ul>

<% if @user.root_comments.present? %>
  <h2>
    Comments
    <%= link_to "Add", new_comment_path(commentable_id: @user.id, commentable_type: 'user') %>
  </h2>
  <%= @user.render_comments %>
<% else %>
  <h4><%= link_to "Add Comment", new_comment_path(commentable_id: @user.id, commentable_type: 'user') %></h4>
<% end %>