config/routes.rb
Rails.application.routes.draw do
  resources :review_years
  root to: "reviews#index"

  scope ':commentable_type' do
    resources :comments
  end

  resources :reviews do
    collection do
      delete :destroy
    end
  end

  resources :users do
    resources :reviews, controller: "users/reviews"
    put "settings", to: "users/settings#update"
  end


  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_commentable
  validates :salary, numericality: true
  validates :level, numericality: true
  devise :rememberable, :trackable, :omniauthable, :omniauth_providers => [:google_oauth2]

  has_many :reviews_for, class_name: "Review", foreign_key: :reviewee_id
  has_many :reviews_by, class_name: "Review", foreign_key: :reviewer_id
  has_settings :user_settings,
               class_name: "UserSetting",
               &UserSetting.default_settings_proc

  def self.find_for_google_oauth2(access_token, _ = nil)
    data = access_token.info
    user = User.where(:email => data['email']).first_or_initialize(new_user_params(data))
    user.save
    user
  end

  def self.new_user_params(data)
    {
        image: data['image'],
        name: data['first_name'],
        salary: 0,
        level: 0
    }
  end

  def all_but_me
    User.where.not(id: self.id)
  end

  def reviews_pending_for
    Review.pending.where(reviewee: self)
  end

  def reviews_done_for
    Review.done.where(reviewee: self)
  end

  def needs_to_write_reviews_for
    Review.pending.where(reviewer: self)
  end

  def only_full_reviews_done_for
    Review.done.where(reviewee: self, is_level_only: false)
  end

  def only_review_levels_done_for
    Review.done.where(reviewee: self, is_level_only: true)
  end

  def average_suggested_level
    self.reviews_for.done.average(:suggested_level)
  end

  def stdev_suggested_level
    suggested_levels = self.reviews_for.done.map(&:suggested_level).compact
    suggested_levels.stdev if suggested_levels.present? && suggested_levels.count > 1
  end

  def can_view_suggested_level_for_user?(user)
    pending_reviews_for = self.reviews_by.pending.pluck(:reviewee_id)
    !pending_reviews_for.include?(user.id)
  end

  def grouped_comments
    self.comment_threads.decorate.group_by(&:parent_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
  end

  def create
    updated_review_params = update_params_with_review_year(review_params)
    Review.find_or_create_by updated_review_params
    render json: {status: :ok}
  end

  def update_params_with_review_year(review_params)
    current_year = Time.now.year.to_s
    review_params.merge!(review_year: ReviewYear.find_or_create_by(name: current_year))
  end

  def destroy
    Review.where(review_params).first!.destroy
    render json: {status: :ok}
  end

  private

  def review_params
    params.permit(:reviewer_id, :reviewee_id)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  skip_before_action :ensure_user_logged_in

  def new_session_path(scope)
    new_user_session_path
  end

  def google_oauth2
    @user = User.find_for_google_oauth2(request.env['omniauth.auth'], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
      sign_in_and_redirect @user, :event => :authentication
    else
      session['devise.google_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/reviews_controller.rb
class Users::ReviewsController < ApplicationController
  def index
    @users = User.all.decorate
  end

  def edit
    @review = Review.find(params[:id]).decorate
  end

  def show
    @review = Review.find(params[:id]).decorate
    @comment = Comment.build_from(@review, current_user.id, nil)
  end

  def update
    @review = Review.find(params[:id])

    if params.key?(:abstain)
      @review.destroy!
      redirect_to :root, notice: 'Review removed successfully!' and return
    end

    @review.assign_attributes(update_if_level_only_review(update_status(review_params)))

    if @review.save
      redirect_to user_review_path(current_user, @review.id), notice: 'Review saved successfully!'
    else
      render :edit
    end
  end

  private

  def update_if_level_only_review(review_params)
    if review_params[:text].strip.blank? && !review_params[:suggested_level].blank?
      review_params.merge(is_level_only: true)
    else
      review_params.merge!(is_level_only: false)
    end

    review_params
  end

  def update_status(review_params)
    if params.key?(:pending)
      review_params.merge!(status: 'pending')
    elsif params.key?(:done)
      review_params.merge!(status: 'done')
    end

    review_params
  end

  def review_params
    params.require(:review).permit(:text, :suggested_level, :is_level_only)
  end
end

app/controllers/users/settings_controller.rb
class Users::SettingsController < ApplicationController
  def update
    current_user.settings(:user_settings).color_scheme
    current_user.settings(:user_settings).update!(color_scheme: params.require(:color_scheme))

    redirect_to :user_reviews
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.decorate
  end

  def show
    @user = User.find(params[:id]).decorate
  end

  def edit
    @user = User.find(params[:id]).decorate
  end

  def update
    @user = User.find(params[:id]).decorate
    if @user.update_attributes(user_params)
      redirect_to users_path, notice: 'User updated!'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:salary, :level, :decided_level)
  end
end

app/views/users/reviews/edit.html.erb
<h3>Write a review for <%= @review.reviewee.decorate.username %></h3>

<%= form_for [current_user, @review] do |f| %>
  <fieldset>
  <%= f.label :text, "Review Text" %>
  <span class="markdown-logo">
    <a href="http://daringfireball.net/projects/markdown/basics" target="_blank">
      <img src="/markdown.png" />
    </a>
  </span>
  <%= f.text_area :text, class: "form-control" %>
  </fieldset>

  <fieldset>
  <%= f.label :text, "Suggested Level" %>
  <div class="row">
    <div class="col-auto">
      <%= f.text_field :suggested_level, class: "form-control review-status-select" %>
    </div>
  </div>
  </fieldset>

  <%= f.submit "Abstain from reviewing", class: "btn btn-warning save-review-btn", name: :abstain, data: { confirm: 'This will destroy your drafted review, continue?' } %>
  <%= f.submit "Save As Draft / Unpublish", class: "btn btn-info save-review-btn", name: :pending %>
  <%= f.submit "Publish", class: "btn btn-primary save-review-btn", name: :done %>
<% end %>

<blockquote class="level_summary">
  <h3 id="l0">Level 0</h3>
  <ul>
    <li>needs a pair or mentor</li>
    <li>can pair and deliver work</li>
    <li>contributes to story (does not only passively participate in pairing)</li>
    <li>learns, reads books; can teach herself independently</li>
    <li>can read and understand small chunks of code independently</li> 
    <li>no sales or hiring expectations</li>    
  </ul>
  
  <h3 id="l0++">Closer to Level 1</h3>
  <ul>
    <li>starting to deliver while pairing</li>
    <li>should understand the basic underlying principles around the processes that the company follows</li>
    <li>for instance, should understand and follow best practices such as checking in code every day, writing tests, getting code reviewed, version control etc</li>
    <li>for instance, should understand agile practices such as story writing, sprints (or whatever the company is following)</li>
  </ul>  

  <h3 id="l1">Level 1</h3>
  <ul>
    <li>can deliver a full feature while pairing with an L0</li>
    <li>can address L0 queries satisfactorily</li>
    <li>can read an existing codebase and start contributing to it</li>
    <li>not expected to rewrite or start a project from scratch</li>
    <li>starting to take sales calls</li>
  </ul>

  <h3 id="l1++">Closer to Level 2</h3>
  <ul>
    <li>contributes to IPMs</li>
    <li>brings something to the table on sales calls</li>
    <li>should have pushed the major chunk of a project to production end-to-end</li>
    <li>understands the rhythm of a project : monitoring, instrumentation</li>
    <li>does not think in terms of just algorithm, also understands about code structure, modularity and reuse.</li>
    <li>familiar with circuit breakers, throttles etc. i.e. contribution is beyond just writing good code</li>
  </ul>

  <h3 id="l2">Level 2</h3>
  <ul>
    <li>can translate a spec into a product</li>
    <li>starting to mentor L0 and L1</li>
    <li>can speak to candidates about nilenso</li>
    <li>can interview effectively, make sound judgements about applicants</li>
    <li>can speak to clients about nilenso, and our work</li>
  </ul>

  <h3 id="l2++">Closer to Level 3</h3>
  <ul>
    <li>can think of a service in a more holistic manner</li>
    <li>can write major chunks of a product from scratch by herself, if needed</li>
    <li>can reason about DB schema, connection interfaces, performance characterists, boxes to run on, load balancers, sharding, tuning the DB etc.</li>
    <li>can make sound proposals on tech stack</li>
  </ul>

  <h3 id="l3">Level 3</h3>
  <ul>
    <li>can work independently and deliver a project if need be</li>
    <li>can translate a business requirement document and deploy a project</li>
    <li>can see cross-product relationships</li>
    <li>thinks about cascading failures and how you negotiate interfaces of other products</li>
    <li>has sound judgement about potential candidates, juniors</li>
    <li>can read past the obvious</li>
    <li>starting to mentor L2, L1, L0</li>
  </ul>

  <h3 id="l3++">Closer to Level 4</h3>
  <ul>
    <li>can think in terms of the eco-system as a whole</li>
    <li>has good judgement around tech stacks around stability, reliability, durability</li>
    <li>can justify tech decisions</li>
    <li>can propose and if need be evangelise changes, bring in new processes, practices, languages</li>
    <li>can generalise knowledge sufficiently (breadth + breadth) to quickly pick up and work on something new</li>
    <li>starting to teach</li>
  </ul>

  <h3 id="l4">Level 4</h3>
  <ul>
    <li>can pitch an architecture</li>
    <li>can reason about the architecture of a solution, and implement it</li>
    <li>can review and reason about choices proposed by L3 and below</li>
  </ul>

  <h3 id="l4++">Closer to Level 5</h3>
  <ul>
    <li>can design and architect a solution</li>
    <li>exercises caution, is prudent in the choices (their choices have greater consequences)</li>
    <li>can substantiate recommendations using experience or proof of concept</li>
    <li>use their knowledge and experience as a multiplier</li>
    <li>more of a coach</li>
  </ul>

  <h3 id="l5">Level 5</h3>
  <ul>
    <li>can own a project (like Insider)</li>
    <li>can read a situation and tailor conversations accordingly</li>
    <li>can convince, impress, inspire</li>
    <li>people skills are very important</li>
  </ul>

  <h3 id="l6">Level 6</h3>
  <ul>
    <li>can handle multiple projects</li>
    <li>sets technical direction based on business requirements</li>
    <li>reviews cross-platform changes</li>
    <li>pitches new products (can be within a project) and processes</li>
  </ul>  
</blockquote>

app/views/users/reviews/index.html.erb
<h2>My Reviews</h2>
<h3>Reviews I Need to Write</h3>
<ul>
  <% Review.pending.where(reviewer: current_user).each do |review| %>
    <li><%= link_to "Write a review for #{review.reviewee.decorate.username}", edit_user_review_path(current_user, review) %></li>
  <% end %>
</ul>
<% if Review.pending.where(reviewer: current_user).empty? %>
  <p>No reviews to write yet.</p>
<% end %>


<h3>Reviews I've Gotten</h3>
<ul>
  <% Review.done.where(reviewee: current_user).each do |review| %>
    <li><%= link_to "From #{review.reviewer.decorate.username}", user_review_path(current_user, review) %></li>
  <% end %>
</ul>
<% if Review.done.where(reviewee: current_user).empty? %>
  <p>No reviews yet.</p>
<% end %>

<h2>Settings</h2>

<h3>I Want to Get Reviews From</h3>
<% @users.each do |user| %>
  <%= react_component("AjaxCheckbox", checked: user.reviews_by.where(reviewee_id: current_user.id).present?,
                      reviewer_id: user.id, reviewee_id: current_user.id, label: user.username) %>
<% end %>
<br>

<h3>Theme</h3>
<%= form_tag(user_settings_path, method: "put") do %>
  <% UserSetting::COLOR_SCHEMES.values.each do |color_scheme| %>
  <div class="form-check">
    <%= radio_button_tag(
          :color_scheme,
          color_scheme,
          current_user.settings(:user_settings).color_scheme == color_scheme,
          class: "form-check-input",
          onclick: "this.form.submit();"
        ) %>
    <%= label_tag("color_scheme_#{color_scheme}", color_scheme.humanize, class: "form-check-label") %>
  </div>
  <% end %>
<% end %>

<br><br>

app/views/users/reviews/show.html.erb
<% content_for :title, "#{@review.reviewer.decorate.username} -> #{@review.reviewee.decorate.username}" %>

<h2>A Review from <%= @review.reviewer.decorate.username %> to <%= @review.reviewee.decorate.username %>
  <% if @review.reviewer == current_user %>
    <%= link_to "Edit", edit_user_review_path(current_user, @review), class: "btn btn-dark btn-sm" %>
  <% end %>
</h2>

<% if @review.suggested_level.present?  %>
  <h5>Suggested Level: <%= @review.suggested_level %></h5>
<% end %>

<%= @review.markdown_text.html_safe %>

<% if @review.root_comments.present? %>
  <h2>
    Comments
    <%= link_to "Add", new_comment_path(commentable_type: 'review', commentable_id: @review.id) %>
  </h2>
  <%= @review.render_comments %>
<% else %>
  <h4><%= link_to "Add Comment", new_comment_path(commentable_type: 'review', commentable_id: @review.id) %></h4>
<% end %>