config/routes.rb
Rails.application.routes.draw do
  resources :review_years
  root to: "reviews#index"

  scope ':commentable_type' do
    resources :comments
  end

  resources :reviews do
    collection do
      delete :destroy
    end
  end

  resources :users do
    resources :reviews, controller: "users/reviews"
    put "settings", to: "users/settings#update"
  end


  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-bs-theme="<%= current_user.settings(:user_settings).color_scheme %>">
  <head>
    <title><%= yield(:title).presence || "Reviews" %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Aleo:wght@400;700&ital@0;1&family=Poppins:wght@300;400;500;700&display=swap">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <% if current_user %>
      <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="/">nilenso reviews</a>
          </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-collapsible">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbar-collapsible">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll">
              <li class="nav-item"><%= link_to "h<span class='#{is_active?(root_path)}'>o</span>me".html_safe, root_path, class: "nav-link #{is_active?(root_path)}" %></li>
              <li class="nav-item"><%= link_to "my dashb<span class='#{is_active?(user_reviews_path(current_user))}'>o</span>ard".html_safe, user_reviews_path(current_user), class: "nav-link #{is_active?(user_reviews_path(current_user))}" %></li>
              <li class="nav-item"><%= link_to "<span class='#{is_active?(users_path)}'>u</span>sers".html_safe, users_path, class: "nav-link #{is_active?(users_path)}" %></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li class="nav-item nav-link">signed in as <%= current_user.decorate.username %></li>
            </ul>
          </div>

        </div>
      </nav>

    <% end %>

    <div class="container main-content">
      <% [:notice, :error, :alert].each do |level| %>
        <% unless flash[level].blank? %>
          <div class="alert <%= flash_class(level) %> alert-dismissible" role="alert">
            <%= content_tag :span, flash[level] %>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        <% end %>
      <% end %>

      <%= yield %>

    </div>

  </body>
</html>